tables:
  exhibitions: 
    Exhibition Title: title
    Exhibition Slug: slug
    exhibition_image_storage_urls: images
    Exhibition Description: description
    Opening Date: opening_date
    Location: location

  Anchor Spaces: 
    Anchor Space Title: title
    Anchor Space Description: description
    anchor_space_image_storage_urls: images

  projects: 
    Project Title: title
    Project Description (Final): description
    project_image_storage_urls: images

  people:
    Person: name
    Slug: slug
    team: Team
    Bio: bio
    headshot_image_storage_url: image
    Company: company
    Display Name: display_name
    Email: email
    First Name: first_name
    Last Name: last_name
    Concatenated Links: social_links
    HoER Contributions: hoer_contributions
    Omega Mart Contributions: omega_mart_contributions
    Convergence Station Contributions: convergence_station_contributions
    The Real Unreal Contributions: the_real_unreal_contributions
    Radio Tave Contributions: radio_tave_contributions
    Display On Site: display_on_site
